version: 2

languages:
  markdown:
    - lint-command: "markdownlint -s"
      lint-stdin: true
      lint-after-open: true
      lint-on-save: true
      lint-formats:
        - "%f:%l %m"
        - "%f:%l:%c %m"
        - "%f: %l: %m"
