complete -c linty -n "__fish_use_subcommand" -s c -l config-path -d 'Optional path to .lintyconfig.json file' -r
complete -c linty -n "__fish_use_subcommand" -l error-on-warning -d 'Treat warnings as errors'
complete -c linty -n "__fish_use_subcommand" -l no-confirm -d 'Print warnings and continue without confirmation'
complete -c linty -n "__fish_use_subcommand" -l ignored -d 'Include files listed in .gitignore and .ignore files'
complete -c linty -n "__fish_use_subcommand" -l hidden -d 'Include hidden files'
complete -c linty -n "__fish_use_subcommand" -l pre-commit -d 'Limit to files staged for commit'
complete -c linty -n "__fish_use_subcommand" -s h -l help -d 'Print help'
complete -c linty -n "__fish_use_subcommand" -s V -l version -d 'Print version'
complete -c linty -n "__fish_use_subcommand" -f -a "init" -d 'Initialize an empty .lintyconfig'
complete -c linty -n "__fish_use_subcommand" -f -a "completions" -d 'Generate shell completions'
complete -c linty -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c linty -n "__fish_seen_subcommand_from init" -s h -l help -d 'Print help'
complete -c linty -n "__fish_seen_subcommand_from completions" -s h -l help -d 'Print help'
complete -c linty -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from help" -f -a "init" -d 'Initialize an empty .lintyconfig'
complete -c linty -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from help" -f -a "completions" -d 'Generate shell completions'
complete -c linty -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
