complete markdownlint -x -s V -l version -d "Print version information"
complete markdownlint -s c -l config -d "Set configuration path"
complete markdownlint -s d -l dot -d "Include dot files"
complete markdownlint -s f -l fix -d "Fix errors"
complete markdownlint -s i -l ignore -d "Ignore errors in files"
complete markdownlint -s j -l json -d "Print output in json format"
complete markdownlint -s o -l output -d "Set output path"
complete markdownlint -s p -l ignore-path -d "Set path to ignorefile"
complete markdownlint -s q -l quiet -d "Suppress output"
complete markdownlint -s r -l rules -d "Set path to rule files"
complete markdownlint -x -s s -l stdin -d "Read from stdin"
complete markdownlint -l enable -d "Enable rules"
complete markdownlint -l disable -d "Disable rules"
complete markdownlint -x -s h -l help -d "Printl help information"