theme = "ayu_dark"

[editor]
line-number = "relative"

[editor.auto-save]
after-delay.enable = true

[editor.lsp]
inlay-hints-length-limit = 20

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true

[keys.normal]
"ret" = "goto_word"
# split navigation (vim-tmux-navigator style)
C-h = 'jump_view_left'
C-j = 'jump_view_down'
C-k = 'jump_view_up'
C-l = 'jump_view_right'
# vim muscle memory
H = 'extend_to_line_start'
L = 'extend_to_line_end'
G = "goto_last_line"
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

[keys.normal.g]
"/" = ["move_prev_word_start", "move_next_word_end", "search_selection", "global_search"]

[keys.normal."space"]
i = ":toggle lsp.display-inlay-hints"

[keys.select]
# vim muscle memory
H = 'extend_to_line_start'
L = 'extend_to_line_end'
