[[language]]
name = "fish"
file-types = ["fish", { glob = "*.fish.tmpl" }]
auto-format = false

[[language]]
name = "typescript"
language-servers = [{ name = "typescript-language-server", except-features = ["format"] }, "oxlint", "oxfmt"]
auto-format = true

[[language]]
name = "tsx"
language-servers = [{ name = "typescript-language-server", except-features = ["format"] }, "oxlint", "oxfmt"]
auto-format = true

[[language]]
name = "javascript"
language-servers = [{ name = "typescript-language-server", except-features = ["format"] }, "oxlint", "oxfmt"]
auto-format = true

[[language]]
name = "jsx"
language-servers = [{ name = "typescript-language-server", except-features = ["format"] }, "oxlint", "oxfmt"]
auto-format = true

[[language]]
name = "json"
formatter = { command = "dprint", args = ["fmt", "--stdin", "json"] }
auto-format = true

[[language]]
name = "html"
formatter = { command = "dprint", args = ["fmt", "--stdin", "html"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = "dprint", args = ["fmt", "--stdin", "css"] }
auto-format = true

[[language]]
name = "markdown"
language-servers = ["marksman", { name = "efm", only-features = ["diagnostics"] }]
formatter = { command = "dprint", args = ["fmt", "--stdin", "markdown"] }
auto-format = true

[[language]]
name = "toml"
formatter = { command = "dprint", args = ["fmt", "--stdin", "toml"] }
auto-format = true

[[language]]
name = "ledger"
scope = "source.ledger"
file-types = ["journal", "ledger", "hledger"]
comment-token = ";"
language-servers = ["ledger-language-server"]

[language-server.ledger-language-server]
command = "ledger-language-server"

[language-server.oxfmt]
command = "oxfmt"
args = ["--lsp"]

[language-server.oxlint]
command = "oxlint"
args = ["--lsp"]

[language-server.efm]
command = "efm-langserver"
