# :schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
email = "rwb@rwblickhan.org"
name = "Russell Blickhan"

[aliases]
e = ["edit"]
l = ["log"]
lb = ["log", "-r", "bookmarks()"]
push = ["git", "push"]

[ui]
diff-formatter = "delta"
default-command = "log"

[merge-tools]
delta.diff-expected-exit-codes = [0, 1]
