#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
email = "rwb@rwblickhan.org"
name = "Russell Blickhan"

[aliases]
e = ["edit"]
l = ["log"]
push = ["git", "push"]
s = ["show"]
sn = ["show", "--name-only"]
