# https://matthiasportzel.com/brewfile/

# litecli
tap "dbcli/tap"

# Better cat
brew "bat"
# Terminal cheatsheets
brew "cheat"
# Structured diffs
brew "difftastic"
# Deno TypeScript runtime
brew "deno"
# sqlite but columnar; also useful as a jq replacement 
brew "duckdb"
# Better du
brew "dust"
# Better ls
brew "eza"
# Better find
brew "fd"
# Better shell
brew "fish"
# Fuzzy finder
brew "fzf"
# GitHub CLI
brew "gh"
# Better diff viewer
brew "git-delta"
# Better curl
brew "httpie"
# Plain-text accounting
brew "hledger"
# git replacement
brew "jj"
# Add a more up-to-date less
brew "less"
# Better sqlite CLI
brew "litecli"
# Interact with LLM APIs easily
brew "llm"
# Markdown linter
brew "markdownlint-cli"
# Mac App Store CLI installer
brew "mas"
# Better vim
brew "neovim"
# Up-to-date node
brew "node"
# Better JS runtime
brew "oven-sh/bun/bun"
# Pandoc document converter
brew "pandoc"
# Install Python executables easily
brew "pipx"
# Better npm
brew "pnpm"
# Better make (for command running, at least)
brew "just"
# Pretty-print json
brew "jq"
# Better grep
brew "ripgrep"
# Better sed
brew "sd"
# Shell linter
brew "shellcheck"
# sqlite utils from simonw
brew "sqlite-utils"
# Command prompt
brew "starship"
# Swift formatting
brew "swiftformat"
# Swift linting
brew "swiftlint"
# Better tail with syntax highlighting
brew "tailspin"
# Rust implementation of tldr shell cheatsheet
brew "tealdeer"
# LaTeX alternative
brew "typst"
# Directory watcher
brew "watchexec"
# Better c
brew "zig"
# Better cd
brew "zoxide"

# Non-Apple display management
cask "betterdisplay"
# Calibre ebook manager
cask "calibre"
# Fira Code / Fira Mono Nerd Fonts
cask "font-fira-code-nerd-font"
cask "font-fira-mono-nerd-font"
# Use rcmd as hyperkey instead
cask "hyperkey"
# Terminal replacement
cask "iterm2"
# Fix mouse scrolling
cask "mac-mouse-fix"
# Better Spotlight
cask "raycast"
# VS Code
cask "visual-studio-code"
# Install Xcode easily
cask "xcodes"
# Zen web browser
cask "zen-browser"
# Zed editor
cask "zed"

mas "GoodLinks", id: 147_433_5294
mas "Fantastical", id: 975_937_182
mas "Hidden Bar", id: 145_245_3066
mas "iA Writer", id: 775_737_590
mas "Things 3", id: 904_280_696
mas "Ulysses", id: 122_557_0693
mas "Velja", id: 160_763_5845

