# https://matthiasportzel.com/brewfile/

# Nerd Fonts
tap "homebrew/cask-fonts"
# Linty
tap "rwblickhan/linty"

# Syntasx-aware sed
brew "ast-grep"
# Better cat
brew "bat"
# Terminal cheatsheets
brew "cheat"
# Better cut
brew "choose-rust"
# Deno TypeScript runtime
brew "deno"
# Better du
brew "dust"
# Better ls
brew "exa"
# Better find
brew "fd"
# Better shell
brew "fish"
# Fuzzy finder
brew "fzf"
# GitHub CLI
brew "gh"
# Better diff viewer
brew "git-delta"
# Better curl
brew "httpie"
# Plain-text accounting
brew "hledger"
# Add a more up-to-date less
brew "less"
# My homegrown linter
brew "linty"
# Interact with LLM APIs easily
brew "llm"
# Markdown linter
brew "markdownlint-cli"
# Better vim
brew "neovim"
# Up-to-date node
brew "node"
# Pandoc document converter
brew "pandoc"
# Install Python executables easily
brew "pipx"
# Better npm
brew "pnpm"
# Better make (for command running, at least)
brew "just"
# Better grep
brew "ripgrep"
# Shell linter
brew "shellcheck"
# Better sed
brew "sd"
# Command prompt
brew "starship"
# Swift formatting
brew "swiftformat"
# Swift linting
brew "swiftlint"
# Better tail with syntax highlighting
brew "tailspin"
# Rust implementation of tldr shell cheatsheet
brew "tealdeer"
# git repo viewer
brew "tig"
# Terminal multiplexer
brew "tmux"
# tmux automation
brew "tmuxinator"
# LaTeX alternative
brew "typst"
# Directory watcher
brew "watchexec"
# Better cd
brew "zoxide"

# Boop toolkit
cask "boop"
# Calibre ebook manager
cask "calibre"
# Datasette desktop application
cask "datasette"
# Fira Code / Fira Mono Nerd Fonts
cask "font-fira-code-nerd-font"
cask "font-fira-mono-nerd-font"
# Route URLs to different browsers
cask "finicky"
# Better Spotlight
cask "raycast"
# VS Code
cask "visual-studio-code"
# Install Xcode easily
cask "xcodes"

# Astro support
vscode "astro-build.astro-vscode"
# Ayu theme
vscode "teabyii.ayu"
# Black formatter for Python
vscode "ms-python.black-formatter"
# Codeium LLM autocomplete
vscode "Codeium.codeium"
# Copy file name command
vscode "nemesv.copy-file-name"
# Deno support
vscode "denoland.vscode-deno"
# Better error highlighting
vscode "usernamehw.errorlens"
# Fish support
vscode "bmalehorn.vscode-fish"
# GitLens to add lots of git features
vscode "eamodio.gitlens"
# GitHub Actions support
vscode "github.vscode-github-actions"
# Shift arguments left / right
vscode "Gruntfuggly.shifter"
# ESLint support
vscode "dbaeumer.vscode-eslint"
# hledger support
vscode "mark-hansen.hledger-vscode"
# justfile support
vscode "skellock.just"
# Better markdown keyboard shortcuts 
vscode "yzhang.markdown-all-in-one"
# markdownlint support
vscode "DavidAnson.vscode-markdownlint"
# MDX support
vscode "unifiedjs.vscode-mdx"
# Prettier formatter for TypeScript
vscode "esbenp.prettier-vscode"
# Better TypeScript error highlighting
vscode "YoavBls.pretty-ts-errors"
# Python support
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
# Typst LSP
vscode "nvarner.typst-lsp"
# Rust support
vscode "rust-lang.rust-analyzer"
# Swift support
vscode "sswg.swift-lang"
# Swiftformat support
vscode "vknabel.vscode-swiftformat"
# Swiftlint support
vscode "vknabel.vscode-swiftlint"
# Tailwind support
vscode "bradlc.vscode-tailwindcss"
# Vim emulation
vscode "vscodevim.vim"
