add_newline = false

[status]
disabled = false
map_symbol = true
format = '[$symbol $status]($style) '

[cmd_duration]
disabled = true

[java]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[swift]
disabled = true
