# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.

# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:
  - trigger: ":date"
    label: "Date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: "rwbg"
    label: "Personal Email"
    replace: "rwblickhan@gmail.com"

  - trigger: "rbv"
    label: "Work Email"
    replace: "russell.blickhan@vanta.com"

  - trigger: ":fingers"
    label: "Fingers"
    replace: "👉👈"

  - trigger: ":newsletter"
    label: "Newsletter Header"
    replace: "---\ntitle:\nlastUpdatedDate: {{mydate}}\npublicationDate: {{mydate}}\nseason: 8\n---\n\n"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":blue4"
    label: "Blue 4"
    replace: "#006DCA"

  # --- hledger

  - trigger: ":apr"
    label: "Amazon Prime Rewards CC (hledger)"
    replace: "liabilities:credit:amazonprimerewards"

  - trigger: ":applecc"
    label: "Apple CC (hledger)"
    replace: "liabilities:credit:apple"

  - trigger: ":applesav"
    label: "Apple Savings (hledger)"
    replace: "assets:banking:apple"

  - trigger: ":chase"
    label: "Chase Banking (hledger)"
    replace: "assets:banking:chase"

  - trigger: ":csr"
    label: "Chase Sapphire Reserve (hledger)"
    replace: "liabilities:credit:chasesapphirereserve"

  - trigger: ":venmo"
    label: "Venmo (hledger)"
    replace: "assets:cash:venmo"
