# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.

# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:
  # --- Dates

  - trigger: ":date"
    label: "Date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # --- Contact info

  - trigger: "rwbg"
    label: "Personal Email"
    replace: "rwblickhan@gmail.com"

  - trigger: "rbv"
    label: "Work Email"
    replace: "russell.blickhan@vanta.com"

  - trigger: ":linkedin"
    label: "LinkedIn Profile"
    replace: "https://www.linkedin.com/in/rwblickhan/"

  - trigger: ":github"
    label: "GitHub Profile"
    replace: "https://github.com/rwblickhan"

  # --- Text

  - trigger: ":fingers"
    label: "Fingers"
    replace: "👉👈"

  - trigger: ":cb"
    label: "Checked Checkbox"
    replace: "- [x]"

  # --- hledger accounts

  - trigger: ":apr"
    label: "Amazon Prime Rewards CC (hledger)"
    replace: "liabilities:credit:amazonprimerewards"

  - trigger: ":applecc"
    label: "Apple CC (hledger)"
    replace: "liabilities:credit:apple"

  - trigger: ":applesav"
    label: "Apple Savings (hledger)"
    replace: "assets:banking:apple"

  - trigger: ":chase"
    label: "Chase Banking (hledger)"
    replace: "assets:banking:chase"

  - trigger: ":csr"
    label: "Chase Sapphire Reserve (hledger)"
    replace: "liabilities:credit:chasesapphirereserve"

  - trigger: ":venmo"
    label: "Venmo (hledger)"
    replace: "assets:cash:venmo"

  # --- Work

  - trigger: ":ffuser"
    label: "Feature Flag Override User ID"
    replace: "rwblickhan-5d3b4e298e932a2a4bb2ec3b"

  - trigger: ":riskflag"
    label: "Reporting Risk Migration Flag Name"
    replace: "reporting_risk_snowflake_migration"

  - trigger: ":agentflag"
    label: "Agent Tool Enabled Flag"
    replace: "reporting_agent_tool_enabled"

  # --- Misc
   
  - trigger: ":newsletter"
    label: "Newsletter Header"
    replace: "---\ntitle:\nlastUpdatedDate: {{mydate}}\npublicationDate: {{mydate}}\nseason: 8\n---\n\n"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":editprompt"
    label: "Editing Prompt"
    replace: "Do a basic editing pass on this newsletter. Check for major factual mistakes, run-on or incomplete sentences, confusing or contradictory sentences, and so on"

  - trigger: ":crosspoint"
    label: "Crosspoint Local URL"
    replace: "http://crosspoint.local/"

  - trigger: ":blue4"
    label: "Blue 4"
    replace: "#006DCA"
