# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.

# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # And much more! For more information, visit the docs: https://espanso.org/docs/

  # --- Migrated from Raycast Snippets ---

  - trigger: "rwbg"
    replace: "rwblickhan@gmail.com"

  - trigger: "rbv"
    replace: "russell.blickhan@vanta.com"

  - trigger: ":fingers"
    replace: "👉👈"

  - trigger: ":cb"
    replace: "- [x]"
